version: '3.8'

#  docker-compose -f docker-compose.dev.yml -p vk up

services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    command: go run app/cmd/main.go
    hostname: 'localhost'
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - env/dev.env
      - env/dev.db.env
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env/dev.db.env

volumes:
  postgres-data: