version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    command: go run app/cmd/main.go
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - dev.env
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - dev.db.env

volumes:
  postgres-data: