version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile.prod
    command: go run app/cmd/main.go
    hostname: 'localhost'
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - env/prod.env
      - env/prod.db.env
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - env/prod.db.env
  # you can set nginx service if you want to make good prod

volumes:
  postgres-data: